version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: uni_support_postgres
    restart: always
    environment:
      POSTGRES_DB: uni_support_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Qwerty7"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  api:
    build: .
    container_name: uni_support_api
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: uni_support_ai
      DB_USER: postgres
      DB_PASSWORD: "@Qwerty7"
      OUTPUT_DIR: outputs
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  dagster:
    build: .
    container_name: uni_support_dagster
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_NAME: uni_support_ai
      DB_USER: postgres
      DB_PASSWORD: "@Qwerty7"
      OUTPUT_DIR: outputs
    ports:
      - "3000:3000"
    volumes:
      - ./outputs:/app/outputs
    command: ["dagster", "dev", "-f", "dagster_pipeline.py", "-h", "0.0.0.0", "-p", "3000"]

volumes:
  postgres_data:
